### ISSUE TITLE
Error: module "rds_boostrap": "mysql_script" is not a valid argument

### ISSUE THREAD

**Issue by vitaliysobur** [fvinas/tf_rds_bootstrap#1]
Hi @fvinas, thank you for creating this repository!
I have a small issue while applying the plan - getting "Error: module "rds_boostrap": "mysql_script" is not a valid argument" error. Can you please advise?
Thanks!

**Comment by fvinas** [comment]
Hi @vitaliysobur, thanks!
Can you please post your terraform code?

**Comment by vitaliysobur** [comment]
I think I have found the issue. In the module you use `sql_script` variable. In the README example you use `my_sql` though. I think it is just a simple typo

**Comment by fvinas** [comment]
Thanks, good spot – just committed the fix (62d4d61307a90a8fde578d5a112d841873cea869)
